Apply suggestions from code review.
Co-authored-by: Bingran Hu <bingran.hu@yscope.com>
Co-authored-by: Junhao Liao <junhao@junhao.ca>

diff --git a/exports/taskfiles/utils/checksum.yaml b/exports/taskfiles/utils/checksum.yaml
--- a/exports/taskfiles/utils/checksum.yaml
+++ b/exports/taskfiles/utils/checksum.yaml
@@ -10,7 +10,7 @@ tasks:
   # @param {string[]} INCLUDE_PATTERNS Path wildcard patterns to compute the checksum for.
   # @param {string[]} [EXCLUDE_PATTERNS] Path wildcard patterns, relative to any `INCLUDE_PATTERNS`,
   # to exclude from the checksum.
-  # @param {string} [FAIL="true"] If set to "false" the task will not fail.
+  # @param {string} [FAIL="true"] If set to "false", the task will not fail.
   compute:
     internal: true
     label: "{{.TASK}}-{{.CHECKSUM_FILE}}"
@@ -39,28 +39,28 @@ tasks:
       - defer: "rm -f '{{.TMP_ERR_LOG}}'"
       - |-
         if ! \
-            {{.ARCHIVER}} \
-            --create \
-            --file - \
-            --group 0 \
-            --mtime "UTC 1970-01-01" \
-            --numeric-owner \
-            --owner 0 \
-            --sort name \
-            --no-anchored \
-            --wildcards \
-            {{- range .EXCLUDE_PATTERNS}}
-            --exclude="{{.}}" \
-            {{- end}}
-            {{- range .INCLUDE_PATTERNS}}
-            {{.}} \
-            {{- end}}
-            2> "{{.TMP_ERR_LOG}}" \
-                | md5sum > "{{.CHECKSUM_FILE}}" \
+          {{.ARCHIVER}} \
+          --create \
+          --file - \
+          --group 0 \
+          --mtime "UTC 1970-01-01" \
+          --numeric-owner \
+          --owner 0 \
+          --sort name \
+          --no-anchored \
+          --wildcards \
+          {{- range .EXCLUDE_PATTERNS}}
+          --exclude="{{.}}" \
+          {{- end}}
+          {{- range .INCLUDE_PATTERNS}}
+          {{.}} \
+          {{- end}}
+          2> "{{.TMP_ERR_LOG}}" \
+            | md5sum > "{{.CHECKSUM_FILE}}" \
         ; then
           rm -f "{{.CHECKSUM_FILE}}"
           {{- if eq "true" .FAIL}}
-            printf "[{{.TASK}} error] failed with:\n%s\n" "$(cat {{.TMP_ERR_LOG}})"
+            printf "[{{.TASK}} error] failed with:\n%s\n" "$(cat '{{.TMP_ERR_LOG}}')"
             exit 1
           {{- else}}
             exit 0
@@ -107,26 +107,26 @@ tasks:
           {{- range .INCLUDE_PATTERNS}}
             for path in {{.}}; do
               test -e "${path}" \
-                  || (
-                    echo "Include path does not exist: ${path}" > "{{$.TMP_ERR_LOG}}"
-                    exit 1
-                  )
+                || (
+                  echo "Include path does not exist: ${path}" > "{{$.TMP_ERR_LOG}}"
+                  exit 1
+                )
             done && \
           {{- end}}
-              (
-                cmp -s "{{.TMP_CHECKSUM_FILE}}" "{{.CHECKSUM_FILE}}" \
-                || (
-                  echo "cmp failed for '{{.TMP_CHECKSUM_FILE}}' '{{.CHECKSUM_FILE}}'" \
-                    > "{{.TMP_ERR_LOG}}"
-                  exit 1
-                  )
-              )
-        ) \
-            || (
-              {{- if eq "true" .FAIL}}
-                printf "[{{.TASK}} error] failed with:\n%s\n" "$(cat {{.TMP_ERR_LOG}})"
+            (
+              cmp -s "{{.TMP_CHECKSUM_FILE}}" "{{.CHECKSUM_FILE}}" \
+              || (
+                echo "cmp failed for '{{.TMP_CHECKSUM_FILE}}' '{{.CHECKSUM_FILE}}'" \
+                  > "{{.TMP_ERR_LOG}}"
                 exit 1
-              {{- else}}
-                rm -f "{{.CHECKSUM_FILE}}"
-              {{- end}}
+                )
             )
+        ) \
+          || (
+            {{- if eq "true" .FAIL}}
+              printf "[{{.TASK}} error] failed with:\n%s\n" "$(cat {{.TMP_ERR_LOG}})"
+              exit 1
+            {{- else}}
+              rm -f "{{.CHECKSUM_FILE}}"
+            {{- end}}
+          )
